### PR TITLE
Identification Documents in Brazil: Concept and Significance

### PR DESCRIPTION
**Pull request by ghost**
Identification Documents in Brazil: Concept and Significance.

### CODE REVIEW

**Review by soxoj — CHANGES_REQUESTED** [review]
Thank you for the update!
I suggest to remove .DS_Store file and .idea folder

**Comment by alexandresantosal91** [comment]
Thank you very much for your suggestion. I have made the change as indicated.

**Comment by soxoj** [comment]
Are you sure you've pushed changes? Don't see new commits

**Comment by soxoj** [comment]
I'll remove unnecessary files manually. Next time, please, make PR from cloned `counter-osint-guide-en` repo

**Comment by soxoj** [comment]
Moved to #17

**Pull request merged**
